config/routes.rb
Rails.application.routes.draw do

  # Nice looking URLs for pagination
  # Add concerns: :paginatable to a resource (with index action) and this will switch the routing for pages.
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  # Admin area and name spaces
  namespace :admin do
    resources :users
    resources :stock_alerts
    resources :watched_stocks
    resources :phone_infos
    resources :stock_lists
    resources :user_settings
    resources :above_average_volumes, controller: 'stock_alerts'
    resources :new52_week_highs, controller: 'stock_alerts'
    resources :new52_week_lows, controller: 'stock_alerts'
    resources :price_decrease_amounts, controller: 'stock_alerts'
    resources :price_decrease_percents, controller: 'stock_alerts'
    resources :price_greater_thans, controller: 'stock_alerts', type: 'PriceGreaterThan'
    resources :price_increase_amounts, controller: 'stock_alerts'
    resources :price_increase_percents, controller: 'stock_alerts'
    resources :price_less_thans, controller: 'stock_alerts'
    resources :price_ranges, controller: 'stock_alerts'

    root to: 'users#index'
  end

  ### PUBLIC PAGES
  get 'public/home'

  get 'public/terms_of_service'

  get 'public/tour'

  resources 'contacts', only: [:new, :create]
   match 'public/contact', to: 'contacts#new', via: 'get'
   match '/contacts', to: 'contacts#new', via: 'get'

  ### SEARCHING
  get 'search', to: 'stock_search#search', as: 'search'
  get 'query', to: 'stock_search#info_query', as: 'query'
  get 'add_watched_stock', to: 'stock_search#add_watched_stock', as: 'add_watched_stock'


  ### RESOURCE ROUTES
  resources :user_settings, only: [:edit, :update] do
    get 'resend_sms_verification_code'
  end

  resources :stock_list, only: [:destroy]

  devise_for :users, controllers: {registrations: 'devise_override/registrations'}

  resources :stock_alerts, except: [:show], concerns: :paginatable do
    # This route should allow for a more regular use of the param :id and makes the :reset_token part of the url and NOT a url param.
    match 'reset_trigger/(:reset_token)' => 'stock_alerts#reset_trigger', :as => :reset_trigger, via: :get, on: :member
  end

  resources :watched_stocks, only: [:index, :show, :destroy], concerns: :paginatable

  # STI StockAlert subclasses - they all route to StockAlertsController

  resources :above_average_volume, controller: 'stock_alerts'
  resources :new52_week_high, controller: 'stock_alerts'
  resources :new52_week_low, controller: 'stock_alerts'
  resources :price_less_than, controller: 'stock_alerts'
  resources :price_greater_than, controller: 'stock_alerts'
  resources :price_decrease_amount, controller: 'stock_alerts'
  resources :price_decrease_percent, controller: 'stock_alerts'
  resources :price_increase_amount, controller: 'stock_alerts'
  resources :price_increase_percent, controller: 'stock_alerts'
  resources :price_range, controller: 'stock_alerts'

  ### ROOT
  root 'public#home'

end

app/models/stock_alert.rb
class StockAlert < ActiveRecord::Base
  include SubType

  ## Relationships
  belongs_to :stock_list

  ## Validations
  validates :stock_list_id, :type, presence: true
  validate :default_value_validation

  ## Scopes
  default_scope { order(:id) }
  scope :with_trigger_status, -> (status) { where(triggered: status) }
  scope :alert_for, -> (stock_list_id) {where(stock_list_id: stock_list_id)}

  ## Pagination for StockAlerts page
  paginates_per 30

  ## Validation methods

  # Validation that if value is required/present that it must be positive
  # @return [Nil] Checks that value is positive - adds an error if not
  def default_value_validation
    if (!value.blank? && BigDecimal(value) < BigDecimal(0)) || (Float(value).nil? rescue true)
      errors.add(:value, I18n.t('models.stock_alerts.validations.positive_value'))
    end
  end

  # Get the StockAlert's WatchedStock (the stock that alerts are triggered on)
  # @return [WatchedStock] the associated watched stock for this alert
  def get_watched_stock
    self.stock_list.watched_stock
  end

  # Master should alert method - checks if the WatchedStock has the proper info for calculation and if the subclass has been triggered and if the triggered flag has been already set before.
  # @return [Boolean] t/f whether the owner of this alert should be alerted
  def should_alert?
    stock = self.get_watched_stock
    self.validate_watched_stock(stock) && self.should_alert(stock) && !self.triggered
  end

  def get_safe_attribute(attr = nil)
    self.send(attr) rescue nil
  end

  # Gets all subtypes without requiring there to be a database entry like descendants or subclasses
  # @return [Array<Class>] Array of the subtypes of StockAlert
  # NOTE: must add any new subtypes here
  def self.subtypes
    [AboveAverageVolume, New52WeekHigh, New52WeekLow, PriceGreaterThan, PriceLessThan, PriceDecreaseAmount, PriceDecreasePercent, PriceIncreaseAmount, PriceIncreasePercent, PriceRange]
  end

  # @return [StockAlert] the stock alert AS its type field
  def as_self_type
    self.becomes(self.type.constantize)
  end

  def preprocess(params = nil)
    nil
    # Do nothing - used for StockAlert types that need to do any preprocessing before validation in controller
  end

  ## TODO Move to a decorator - debating if should - seems like a lot of work for minimal benefit (3/12/17)
  ## Subclass methods - implemented by all subclasses
  # Only documented here for brevity

  # Value to show users when creating/editing stock alerts
  # @return [String] the select box value to show when creating/editing stock alerts
  def self.select_text
    raise 'Not implemented'
  end

  # Links to the en.yml file for translations
  # @return [String] the universal name of a partial (used in mailers, sms, forms)
  def self.partial_name
    raise 'Not implemented'
  end

  # Helper to get to self.partial (avoid errors because forgot to call on the class rather than the object)
  # @return [String] the universal name of a partial (used in mailers, sms, forms)
  def partial_name
    self.class.partial_name
  end

  # Text to display when viewing already created stock alerts (alert when... {what happens})
  # Populated by view_params and short_view_params
  # @return [String] raw un-formatted text
  def view_text
    raise 'Not implemented'
  end

  # Populates view_text
  # Array of formatters for various values to insert params into the view_text
  # @return [Array<Formatter>] the formatters to format view_text
  def view_params
    raise 'Not implemented'
  end

  # Populates view_text
  # Array of formatters for various values to insert params into the view_text
  # @return [Array<Formatter>] the formatters to format view_text
  def short_view_params
    raise 'Not implemented'
  end

  # These methods should only be called within the context of StockAlert or subclasses
  protected

  # Should the alert be triggered according to this stock alert subclass
  # This method assumes the stock is present and that the WatchedStock has been validated
  # @param [WatchedStock] stock the stock to validate
  # @return [Boolean] whether or not to alert - at a subclass level
  def should_alert(stock)
    raise 'Not implemented'
  end

  # Check if the watched stock has the required data to perform the calculation (as values may be nil)
  # @param [WatchedStock] stock the stock to validate
  # @return [Boolean] true if the stock has present all the attributes that are necessary to perform the alert calculation
  def validate_watched_stock(stock)
    raise 'Not implemented'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  ## Validations
  validates :first_name, :last_name, presence: true
  validates_associated :stock_lists, :user_setting

  ## Devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  ## Relationships
  has_many :stock_lists, dependent: :destroy
  has_one :user_setting, dependent: :destroy

  ## Callbacks
  after_create :attach_settings

  # @return [String] users 'full name'
  def full_name
    self.first_name + ' ' + self.last_name
  end

  # Get all user's stock alerts
  # @return [Array<StockAlert>]
  def get_stock_alerts
    StockAlert.joins(:stock_list).where('stock_lists.user_id = ?', self.id)
  end

  # Get all of a user's watched stocks (as stocklists but they are preloaded)
  # @return [Array<StockList>]
  def get_watched_stocks
    self.stock_lists.includes(:watched_stock, :stock_alerts)
  end

  # Customization on how to send the Devise mail - now or later
  # @return [Nil] Mailer for Devise
  # TODO test - was there a reason for this to be deliver_now?
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  private

  # Ensure every user has a user_settings (default email to true, sms to false)
  # @return [Boolean] t/f if the record saved
  def attach_settings
    setting = self.build_user_setting(alert_sms: false, alert_email: true)
    setting.save
  end

end

app/controllers/admin/stock_alerts_controller.rb
module Admin
  class StockAlertsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = StockAlert.
    #     page(params[:page]).
    #     per(10)
    # end

    # Need a custom find_resource because of the inheritance with StockAlerts.
    # For validation purposes we need to validate the class as itself, not what it was before.
    # This is only done when there is a type parameter in the stock_alert hash parameter (on Create)
    # Else the default behavior is used
    def find_resource(param)
      if !params[:stock_alert].nil?
        type = params[:stock_alert][:type]
        found = resource_class.find(param)
        found.nil? ? found : found.becomes(type.constantize)
      else
        resource_class.find(param)
      end
    end

  end
end

app/controllers/stock_alerts_controller.rb
class StockAlertsController < ApplicationController
  ##
  ### CALL BACKS
  ##

  before_action :set_stock_alert, only: [:edit, :update, :destroy] # Set the @stock_alert variable for these actions
  before_action :compile_watched_stock_select, only: [:new, :edit]
  before_action :preprocess_params, only: [:create, :update]
  skip_before_action :authenticate_user!, only: [:reset_trigger] # Do not require authentication for reset_trigger. Authenticated via the 'reset_token' param.

  ##
  ### CRUD + I (index)
  ##

  # GET /stock_alerts
  # Show stock alerts either filtered by the stock list id (filter by a specific stock (TSLA) and only show alerts for that stock) or show all the alerts a user has.
  # Params
  # stock_list_id - ID of the stock list the stock alerts should be filtered by
  # @return [Array<StockAlert>] stock alerts for the user (possibly filtered)
  def index
    stock_alerts = current_user.get_stock_alerts
    filtering_params(params).each do |key, value|
      stock_alerts = stock_alerts.public_send(key, value) if value.present? && !stock_alerts.empty?
    end
    filtered_stock_alerts = stock_alerts.map { |alert| alert.decorate } # decorate each with its own type of decorator
    @stock_alerts = Kaminari.paginate_array(filtered_stock_alerts).page(params[:page]).per(StockAlert.default_per_page) # uses the paginates_per setting on the model
  end

  # GET /stock_alerts/new
  # Create a new stock alert
  # Prep for creation of stock alerts
  # Params
  # stock_list_id - ID of the stock list to associate this stock alert with
  # @return [StockAlert] newly created stock alert with associated WatchedStock already attached and loaded
  def new
    # When creating a new stock alert a hidden field is populated with the stock_list_id (to associate the stock alert with the correct stock)
    @stock_alert = StockAlert.new(stock_list_id: params[:alert_for])
  end

  # GET /stock_alerts/1/edit
  # Edit a stock alert
  # Params
  # id - ID of the stock alert to work with (populate @stock_alert)
  def edit
    # Don't need to explicitly get the WatchedStock due to set_stock_alert()
  end

  # POST /stock_alerts
  # Create a stock alert
  # TODO check that all translations are showing up correctly
  def create
    @stock_alert = StockAlert.new(stock_alert_params) # filter out disallowed params
    if @stock_alert.save
      # If save success return a success notice, return to stock alerts path (to show the new alert)
      redirect_to stock_alerts_path, notice: t('controller.stock_alerts.flash.create.success')
    else
      # if failed populate the select list
      compile_watched_stock_select
      render :new
    end
  end

  # PATCH/PUT /stock_alerts/1
  # Update existing stock alerts
  # Params
  # id - ID of the stock alert to work with (populate @stock_alert)
  def update
    if @stock_alert.update_with_type_validations(stock_alert_params) # updates based on the updated type not the old type
      # On success redirect to index with success
      redirect_to stock_alerts_path, notice: t('controller.stock_alerts.flash.update.success')
    else
      # redirect to edit on error
      # Don't need to explicitly get the WatchedStock due to set_stock_alert()
      # if failed populate the select list
      compile_watched_stock_select
      render :edit
    end
  end

  # DELETE /stock_alerts/1
  # Delete a stock alert
  # Params
  # id - ID of the stock alert to work with (populate @stock_alert)
  def destroy
    # destroy the stock alert and provide a confirm message
    @stock_alert.destroy
    redirect_to stock_alerts_url, notice: t('controller.stock_alerts.flash.destroy.success')
  end

  ##
  ### CUSTOM ACTIONS
  ##

  # Reset the stock alert so that it can be triggered again and send out alerts
  # This method allows a user to reset the trigger via link and even while not signed in
  # It will validate the user is allowed to reset the trigger by the reset_token
  # Note: the reset token is reset each time the stock alert it triggered (has a different reset token) this means that old links to reset a particular stock alert will not work. This method allows users to reset stock alerts without having to login (email or sms).
  # Idempotent - can use the same link multiple times without side effects (once it is reset once it cannot be reset again - it is just re-saving the same data)
  #
  # Params
  # stock_alert_id - ID of the stock alert to reset
  # reset_token - the token that confirms this user is allowed to reset the stock alert
  def reset_trigger
    # get data
    @stock_alert = StockAlert.find(params[:id])
    @reset_token = params[:reset_token]
    # determine if the reset is valid # Don't accept blank reset_tokens
    is_valid_reset_request = @stock_alert.reset_token == @reset_token && !@reset_token.blank?
    # determine if the user is logged in (where to take them after reset)
    redirect_location = user_signed_in? ? stock_alerts_path : root_path # location to redirect too
    # determine if the reset is successful
    reset_successful = is_valid_reset_request ? @stock_alert.update(triggered: false) : false
    # determine the text to show the user
    reset_text = reset_successful ? t('controller.stock_alerts.actions.reset_trigger.success') : t('controller.stock_alerts.actions.reset_trigger.error')
    # determine the notice type to show the user
    reset_notice = reset_successful ? {notice: reset_text} : {alert: reset_text}
    # redirect and provide correct redirect/popup
    redirect_to redirect_location, reset_notice
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  # Set the stock alert being worked on in one place (reduce code duplication)
  def set_stock_alert
    @stock_alert = StockAlert.find(params[:id])
    @stock = @stock_alert.get_watched_stock
  end

  # Never trust parameters from the scary internet, only allow the white list through. Filters out disallowed params
  # NOTE: add new parameters here (ex. reset_token) when adding new params to StockAlerts
  def stock_alert_params
    params.require(:stock_alert).permit(:stock_list_id, :reset_token, :id, :value, :alert_name, :type)
  end

  def preprocess_params
    alert = StockAlert.new(stock_alert_params)
    alert.preprocess(params)
  end

  # Provides list of params to filter alerts by. Linked to StockAlert model scopes.
  def filtering_params(params)
    params.slice(:with_trigger_status, :alert_for)
  end

  def compile_watched_stock_select
    @stock_list_ids = current_user.get_watched_stocks.collect { |li| [li.watched_stock.name, li.id] }
  end

end

app/helpers/stock_alerts_helper.rb
module StockAlertsHelper
  # TODO test
  # @param [Object] alert_type StockAlert subclass object or Class
  # @param [Form] form ActiveRecord form
  # @return [View]  Renders the partial
    def render_alert_form(alert_type, form)
      render "/stock_alerts/alert_forms/#{alert_type.partial_name}", f: form
    end
end

app/views/stock_alerts/_form.html.erb
<%= form_for(@stock_alert.becomes(StockAlert)) do |f| %>
    <br/>
    <%= f_row do %>
        <%= f_columns([:medium_12]) do %>
            <h2><%= t('views.stock_alerts.form.title') %></h2>
        <% end %>
    <% end %>

    <%= form_error_helper(@stock_alert) %>

    <%= f_row do %>
        <%= f_columns([:large_6, :medium_8, :small_12]) do %>
            <%= f.select :type, StockAlert.subtypes.collect {|klass| [klass.select_text, klass.name]}, include_blank: true %>
        <% end %>
        <%= f_columns([:large_6, :medium_4, :small_12], {id: 'stock_alert_input'}) do %>
            <!-- Space for specific stock alert form partial to be added based on selected stock alert desired -->
        <% end %>
    <% end %>
    <%= f_row do %>
        <%= f_columns([:large_1, :medium_1, :small_2]) do %>
            <h3><%= 'for' %></h3>
        <% end %>
        <%= f_columns([:large_5, :medium_7, :small_10, :end]) do %>
            <%= f.select :stock_list_id, @stock_list_ids, include_blank: true %>
        <% end %>
    <% end %>
    <%= f_row do %>
        <%= f_columns([:large_2, :medium_3, :small_12]) do %>
            <h3><%= 'with name' %></h3>
        <% end %>
        <%= f_columns([:large_4, :medium_5, :small_12, :end]) do %>
            <%= f.text_field :alert_name, placeholder: t('views.stock_alerts.form.optional_field') %>
        <% end %>
    <% end %>

    <!-- Cannot move the selectInput out to another file due to the dependency on the form (f) variable in the erb code. -->
    <script>
        // Reduce duplication
        var stock_alert_type = '#stock_alert_type';
        var stock_alert_input = '#stock_alert_input';
        // On document ready then render the appropriate partial
        $(document).ready(function () {
            selectInput()
        });
        // Render the appropriate partial on change
        $(stock_alert_type).change(function () {
            selectInput()
        });

        function selectInput() {
            $(stock_alert_input).empty(); // Clear out previous partials/input
            var selected = $(stock_alert_type).val();
            var toRender = "";
            switch (selected) {
                // Figure out which partial to show
                // The partials are rendered on the server before being sent over - the JS just chooses which to show - so there is a performance penalty for having to show all the options
                case 'AboveAverageVolume':
                    toRender = "<%= j render_alert_form(AboveAverageVolume, f) %>";
                    break;
                case 'New52WeekHigh':
                    toRender = "<%= j render_alert_form(New52WeekHigh, f) %>";
                    break;
                case 'New52WeekLow':
                    toRender = "<%= j render_alert_form(New52WeekLow, f) %>";
                    break;
                case 'PriceGreaterThan':
                    toRender = "<%= j render_alert_form(PriceGreaterThan, f) %>";
                    break;
                case 'PriceLessThan':
                    toRender = "<%= j render_alert_form(PriceLessThan, f) %>";
                    break;
                case 'PriceDecreaseAmount':
                    toRender = "<%= j render_alert_form(PriceDecreaseAmount, f) %>";
                    break;
                case 'PriceDecreasePercent':
                    toRender = "<%= j render_alert_form(PriceDecreasePercent, f) %>";
                    break;
                case 'PriceIncreaseAmount':
                    toRender = "<%= j render_alert_form(PriceIncreaseAmount, f) %>";
                    break;
                case 'PriceIncreasePercent':
                    toRender = "<%= j render_alert_form(PriceIncreasePercent, f) %>";
                    break;
                case 'PriceRange':
                    toRender = "<%= j render_alert_form(PriceRange, f) %>";
                    break;
                // ADD NEW TYPES HERE
                default:
                    toRender = "";
            }
            if (toRender) { // if there is something to render - render it
                $(stock_alert_input).append(toRender); // input new partial for selected stock alert
            }
        }
    </script>

    <div class="actions">
      <%= f.submit class: 'button small' %>
    </div>

<% end %>

app/views/stock_alerts/_stock_alert_listing_table.html.erb
<table>
  <thead>
  <tr>
    <th><%= t('views.stock_alerts.index.table.headers.column1') %></th>
    <th><%= t('views.stock_alerts.index.table.headers.column2') %></th>
    <th><%= t('views.stock_alerts.index.table.headers.column3') %></th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @stock_alerts.each do |stock_alert| %>
      <tr>
        <td><%= stock_alert.alert_name %> </td>
        <td><%= stock_alert.description %></td>
        <td><%= stock_alert.triggered %>
          <strong><%= link_to t('general.actions.reset'), reset_trigger_stock_alert_path(id: stock_alert, reset_token: stock_alert.reset_token) unless !stock_alert.triggered %></strong>
        </td>
        <td><%= dropdown_helper(stock_alert.class.to_s + stock_alert.id.to_s, t('views.stock_alerts.index.options.label'), [
            (link_to t('general.actions.edit'), edit_stock_alert_path(stock_alert)),
            (link_to t('general.actions.delete'), stock_alert, method: :delete, data: {confirm: t('general.confirm.are_you_sure')})
        ], 'tiny') %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/stock_alerts/_stock_alerts_listing_accordion.html.erb
<ul class="accordion" data-accordion>
  <% @stock_alerts.each do |stock_alert| %>
      <li class="accordion-navigation">
        <a href="#stock_alert_<%=stock_alert.id%>"><%= stock_alert.unlinked_description %></a>
        <div id="stock_alert_<%=stock_alert.id%>" class="content">
          <p>Alert name: <%= stock_alert.alert_name %></p>
          <p>Is triggered: <%= stock_alert.triggered %>
            <strong><%= link_to t('general.actions.reset'), reset_trigger_stock_alert_path(id: stock_alert, reset_token: stock_alert.reset_token) unless !stock_alert.triggered %></strong></p>
          <%= link_to t('general.actions.edit'), edit_stock_alert_path(stock_alert), class: 'tiny button' %>
          <%= link_to t('general.actions.delete'), stock_alert, method: :delete, data: {confirm: t('general.confirm.are_you_sure')}, class: 'tiny button' %>
        </div>
      </li>
  <% end %>
</ul>
<%= paginate @stock_alerts %>

app/views/stock_alerts/edit.html.erb
<%= render 'form' %>

<%= link_to t('general.actions.back'), stock_alerts_path %>

app/views/stock_alerts/index.html.erb
<h2><%= t('views.stock_alerts.index.title') %></h2>
<%= f_row do %>
    <%= f_columns([:small_12, :medium_2]) do %>
        <%= dropdown_helper('filter', t('views.stock_alerts.index.filter.title'),
                            [link_to(t('views.stock_alerts.index.filter.filter1'), stock_alerts_path(alert_for: params[:alert_for])),
                             link_to(t('views.stock_alerts.index.filter.filter2'), stock_alerts_path(with_trigger_status: true, alert_for: params[:alert_for])),
                             link_to(t('views.stock_alerts.index.filter.filter3'), stock_alerts_path(with_trigger_status: false, alert_for: params[:alert_for])),
                             link_to(t('views.stock_alerts.index.filter.filter4'), stock_alerts_path)], 'tiny') %>
    <% end %>
    <%= f_columns([:small_8, :medium_5]) do %>
        <%= page_entries_info @stock_alerts, entry_name: t('models.stock_alerts.name.single').downcase %>
    <% end %>
    <%= f_columns([:small_4, :medium_2, :end]) do %>
        <%= link_to t('views.stock_alerts.index.new.text'), new_stock_alert_path, class: 'tiny button' %>
    <% end %>
<% end %>

<!-- Conditional visibility based on screen size -->
<div class="show-for-medium-up">
  <%= render 'stock_alert_listing_table' %>
</div>

<div class="show-for-small-only">
  <%= render 'stock_alerts_listing_accordion' %>
</div>

app/views/stock_alerts/new.html.erb
<%= render 'form' %>

<%= link_to t('general.actions.back'), watched_stocks_path %>