config/routes.rb
Rails.application.routes.draw do

  # Nice looking URLs for pagination
  # Add concerns: :paginatable to a resource (with index action) and this will switch the routing for pages.
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  # Admin area and name spaces
  namespace :admin do
    resources :users
    resources :stock_alerts
    resources :watched_stocks
    resources :phone_infos
    resources :stock_lists
    resources :user_settings
    resources :above_average_volumes, controller: 'stock_alerts'
    resources :new52_week_highs, controller: 'stock_alerts'
    resources :new52_week_lows, controller: 'stock_alerts'
    resources :price_decrease_amounts, controller: 'stock_alerts'
    resources :price_decrease_percents, controller: 'stock_alerts'
    resources :price_greater_thans, controller: 'stock_alerts', type: 'PriceGreaterThan'
    resources :price_increase_amounts, controller: 'stock_alerts'
    resources :price_increase_percents, controller: 'stock_alerts'
    resources :price_less_thans, controller: 'stock_alerts'
    resources :price_ranges, controller: 'stock_alerts'

    root to: 'users#index'
  end

  ### PUBLIC PAGES
  get 'public/home'

  get 'public/terms_of_service'

  get 'public/tour'

  resources 'contacts', only: [:new, :create]
   match 'public/contact', to: 'contacts#new', via: 'get'
   match '/contacts', to: 'contacts#new', via: 'get'

  ### SEARCHING
  get 'search', to: 'stock_search#search', as: 'search'
  get 'query', to: 'stock_search#info_query', as: 'query'
  get 'add_watched_stock', to: 'stock_search#add_watched_stock', as: 'add_watched_stock'


  ### RESOURCE ROUTES
  resources :user_settings, only: [:edit, :update] do
    get 'resend_sms_verification_code'
  end

  resources :stock_list, only: [:destroy]

  devise_for :users, controllers: {registrations: 'devise_override/registrations'}

  resources :stock_alerts, except: [:show], concerns: :paginatable do
    # This route should allow for a more regular use of the param :id and makes the :reset_token part of the url and NOT a url param.
    match 'reset_trigger/(:reset_token)' => 'stock_alerts#reset_trigger', :as => :reset_trigger, via: :get, on: :member
  end

  resources :watched_stocks, only: [:index, :show, :destroy], concerns: :paginatable

  # STI StockAlert subclasses - they all route to StockAlertsController

  resources :above_average_volume, controller: 'stock_alerts'
  resources :new52_week_high, controller: 'stock_alerts'
  resources :new52_week_low, controller: 'stock_alerts'
  resources :price_less_than, controller: 'stock_alerts'
  resources :price_greater_than, controller: 'stock_alerts'
  resources :price_decrease_amount, controller: 'stock_alerts'
  resources :price_decrease_percent, controller: 'stock_alerts'
  resources :price_increase_amount, controller: 'stock_alerts'
  resources :price_increase_percent, controller: 'stock_alerts'
  resources :price_range, controller: 'stock_alerts'

  ### ROOT
  root 'public#home'

end

app/controllers/stock_search_controller.rb
class StockSearchController < ApplicationController
  # Search for a stock
  # Uses the StockDataInterface (which connects to the stock data API we use) to retrieve the data on a particular stock
  # Params
  # q - query string to search for
  # @return [Array<Hash>] with data on the stock (semi raw from API) or empty array if no results
  def search
    if params.has_key?(:q)
      @symbols = StockDataInterface.search(params[:q])
    else
      @symbols = []
    end
  end

  # TODO Test
  # Get information on an asset/company and return JSON for frontend
  # Takes :ticker param for now to search for stock data
  # @return [String] JSON data of the WatchedStockDecorator
  def info_query
    result = if params.has_key?(:ticker)
               exists = WatchedStock.find_by_ticker(params[:ticker])
               stock = if exists.nil?
                         WatchedStock.new_from_stock_data(StockDataInterface.get_quotes(params[:ticker]).first)
                       else
                         exists
                       end
               stock.decorate
             else
               nil
             end
    render :json => result
  end

  #TODO verify that translations are working
  # Design note: though this method creates a stock list it also creates a watched stock and uses search data. It makes it difficult to decide on a 'best' place to have this method. As a result it was determined to stay in the SearchController mainly because it was already here and in the end the method renders search.
  # Add a stock to the watch list (stock list) for a user
  # In reality this method adds a stock to the WatchedStock table, a table that is used by all users to prevent duplication of data. This method adds a new WatchedStock or finds an existing record.
  # This method will query data for the stock to watch, create a WatchedStock if needed, then create a StockList to match the user to the WatchedStock (if it does not already exist)
  # Params
  # to_watch - String - Ticker of stock to watch
  def add_watched_stock
    if params.has_key?(:to_watch)
      watch = params[:to_watch]
      data = StockDataInterface.get_quotes([watch]).first
      stock = WatchedStock.init_from_stock_data(data).find_or_create_by(ticker: watch)
      if stock.errors.empty? && StockList.find_or_create_by(user_id: current_user.id, watched_stock_id: stock.id) # checks that stock exists and creates new StockList record. This action is idempotent (will not double create)
        flash.now[:success] = t('controller.stock_search.actions.add_watched_stock.success')
      else
        puts 'Error in saving new watched stock: ' + stock.errors.messages.to_s
        flash.now[:alert] = t('controller.stock_search.actions.add_watched_stock.error.missing_data')
      end
    else
      puts 'Could not add watched stock because :to_watch param was missing.'
      flash.now[:alert] = t('controller.stock_search.actions.add_watched_stock.error.general')
    end
    render :search # return to search page after adding the stock
  end

end

app/helpers/stock_search_helper.rb
module StockSearchHelper
end

app/views/stock_search/_search_main.html.erb
<%= form_tag('/search', method: 'get') do %>
    <div class="row collapse">
      <!-- search_size defined as a variable passed to the partial -->
      <div class="small-9 large-9 columns">
        <%= text_field_tag(:q, nil, placeholder: t('views.shared.search.placeholder')) %>
      </div>
      <div class="small-3 large-3 columns">
        <%= button_tag(icon_helper('magnifying-glass', :inline) + ' ' + t('views.shared.search.button'), class: 'button postfix') %>
      </div>
    </div>
<% end %>

app/views/stock_search/_search_topbar.html.erb
<%= form_tag('/search', method: 'get') do %>
    <div class="row collapse">
      <!-- search_size defined as a variable passed to the partial -->
      <div class="small-7 columns">
        <%= text_field_tag(:q, nil, placeholder: t('views.shared.search.placeholder')) %>
      </div>
      <div class="small-5 columns">
        <%= button_tag(icon_helper('magnifying-glass', :inline) + ' ' + t('views.shared.search.button'), class: "search_box") %>
      </div>
    </div>
<% end %>

app/views/stock_search/search.html.erb
<br/>

<%= render 'search_main' %>


<br/>

<% if @symbols.present? && !@symbols.empty? %>
    <h3><%= t('views.stock_search.search.title') %></h3>
    <% @symbols.each do |sym| %>
        <%= f_row do %>
            <hr/>
            <!-- Name/Info -->
            <%= f_columns([:medium_7]) do %>
                <h5><%= sym[:name] %> (<%= sym[:symbol] %>)</h5>
            <% end %>
            <!-- Actions -->
            <%= f_columns([:medium_5]) do %>
                <ul class="button-group right">
                  <%= link_to icon_helper('eye', :inline) + ' ' + t('views.stock_search.search.watch_stock'), add_watched_stock_path(to_watch: sym[:symbol]), class: 'small button' %>
                  <%= link_to icon_helper('info', :inline) + ' ' + 'More Info', '#', class: 'small button stock_info', :'data-link' => sym[:symbol], :'data-reveal-id' => 'more_info_modal' %>
                </ul>
            <% end %>
        <% end %>
    <% end %>
<% else %>
    <p><%= t('views.stock_search.search.no_results') %></p>
<% end %>
<%= render 'shared/more_asset_info' %>

<script>
  // On click of a stock_info class link the data-link field contains the ticker and that will be searched and populate a modal.
    $(".stock_info").click(function () {
        var ticker = this.getAttribute("data-link");
        getAssetInfo(ticker, populateAssetInfo);

        // Should we also trigger the modal here instead of the link?
        // $('#search_info_modal').foundation('reveal', 'open');
        // Answer: No, when triggering it via JS it does not know what position to be at when the modal is triggered so the user may not see it
    });
</script>