config/routes.rb
Rails.application.routes.draw do

  # Nice looking URLs for pagination
  # Add concerns: :paginatable to a resource (with index action) and this will switch the routing for pages.
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  # Admin area and name spaces
  namespace :admin do
    resources :users
    resources :stock_alerts
    resources :watched_stocks
    resources :phone_infos
    resources :stock_lists
    resources :user_settings
    resources :above_average_volumes, controller: 'stock_alerts'
    resources :new52_week_highs, controller: 'stock_alerts'
    resources :new52_week_lows, controller: 'stock_alerts'
    resources :price_decrease_amounts, controller: 'stock_alerts'
    resources :price_decrease_percents, controller: 'stock_alerts'
    resources :price_greater_thans, controller: 'stock_alerts', type: 'PriceGreaterThan'
    resources :price_increase_amounts, controller: 'stock_alerts'
    resources :price_increase_percents, controller: 'stock_alerts'
    resources :price_less_thans, controller: 'stock_alerts'
    resources :price_ranges, controller: 'stock_alerts'

    root to: 'users#index'
  end

  ### PUBLIC PAGES
  get 'public/home'

  get 'public/terms_of_service'

  get 'public/tour'

  resources 'contacts', only: [:new, :create]
   match 'public/contact', to: 'contacts#new', via: 'get'
   match '/contacts', to: 'contacts#new', via: 'get'

  ### SEARCHING
  get 'search', to: 'stock_search#search', as: 'search'
  get 'query', to: 'stock_search#info_query', as: 'query'
  get 'add_watched_stock', to: 'stock_search#add_watched_stock', as: 'add_watched_stock'


  ### RESOURCE ROUTES
  resources :user_settings, only: [:edit, :update] do
    get 'resend_sms_verification_code'
  end

  resources :stock_list, only: [:destroy]

  devise_for :users, controllers: {registrations: 'devise_override/registrations'}

  resources :stock_alerts, except: [:show], concerns: :paginatable do
    # This route should allow for a more regular use of the param :id and makes the :reset_token part of the url and NOT a url param.
    match 'reset_trigger/(:reset_token)' => 'stock_alerts#reset_trigger', :as => :reset_trigger, via: :get, on: :member
  end

  resources :watched_stocks, only: [:index, :show, :destroy], concerns: :paginatable

  # STI StockAlert subclasses - they all route to StockAlertsController

  resources :above_average_volume, controller: 'stock_alerts'
  resources :new52_week_high, controller: 'stock_alerts'
  resources :new52_week_low, controller: 'stock_alerts'
  resources :price_less_than, controller: 'stock_alerts'
  resources :price_greater_than, controller: 'stock_alerts'
  resources :price_decrease_amount, controller: 'stock_alerts'
  resources :price_decrease_percent, controller: 'stock_alerts'
  resources :price_increase_amount, controller: 'stock_alerts'
  resources :price_increase_percent, controller: 'stock_alerts'
  resources :price_range, controller: 'stock_alerts'

  ### ROOT
  root 'public#home'

end

app/models/watched_stock.rb
class WatchedStock < ActiveRecord::Base

  ## Relationships
  has_many :stock_lists

  ## Validations
  validates :name, :ticker, presence: true, uniqueness: true # NOTE: only ticker uniqueness is DB enforced (and indexed)

  # Other fields are not currently validated because they may not be present for all stocks.

  # TODO after adding validations - test
  validates_associated :stock_lists

  ## Scopes
  # TODO test
  default_scope { order(:ticker) }

  # TODO test
  # Url to the watched stock image (company logo usually)
  # @return [String] url
  def image_url
    if self.blank?
      CompanyDataInterface.default_company.get_company_logo_url
    else
      self.image_url
    end
  end

  # TODO test
  # Sets attributes to use when creating a new WatchedStock for the first time
  # NOTE: Only use this to initiate fields before a create (DOES NOT RETURN A USABLE OBJECT)
  # Example use: StockSearchController.add_watched_stock
  # @param [StockDataInterface] data the data to convert into a partial WatchedStock
  # @return [WatchedStock::Relation]
  def self.init_from_stock_data(data)
    WatchedStock.create_with(map_stock_data(data))
  end

  # TODO test
  # Method to update attributes of existing stock
  # @param [StockDataInterface] new
  # @return [boolean] if the update succeeded
  def update_from_stock_data(new)
    temp_prev_52_high = week_52_high # save the prev before overwriting it
    temp_prev_52_low = week_52_low
    partial_update = self.class.map_stock_data(new)
    # To handle a migration issue where the prev high/low were causing saving errors. This is a good precaution to have moving forward.
    to_merge = if temp_prev_52_high.nil? || temp_prev_52_low.nil?
                 {}
               else
                 {prev_week_52_high: temp_prev_52_high,
                  prev_week_52_low: temp_prev_52_low}
               end
    full_update = partial_update.merge(to_merge)
    self.update(full_update)
  end

  # TODO test
  # Init a new watched stock from stock data interface
  # @param [StockDataInterface] new the data to populate a watched stock with
  # @return [WatchedStock] a new watched stock (unsaved)
  def self.new_from_stock_data(new)
    self.new(map_stock_data(new))
  end

  private

  # Helper to map StockDataInterface data to WatchedStock fields
  # @param [StockDataInterface] data
  # @return [Hash<String, String>] Mapped data
  def self.map_stock_data(data)
    {name: data.name,
     ticker: data.ticker,
     current_price: data.bid,
     last_price: data.last_price,
     change: data.change,
     change_percentage: data.change_percentage,
     volume: data.volume,
     average_volume: data.average_volume,
     open: data.open,
     high: data.high,
     low: data.low,
     close: data.close,
     prev_close: data.prev_close,
     week_52_high: data.week_52_high,
     week_52_low: data.week_52_low,
     prev_week_52_high: data.week_52_high,
     prev_week_52_low: data.week_52_low,
     asset_type: data.asset_type} unless data.nil?
  end
end

app/controllers/admin/watched_stocks_controller.rb
module Admin
  class WatchedStocksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = WatchedStock.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   WatchedStock.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/watched_stocks_controller.rb
class WatchedStocksController < ApplicationController
  ##
  ### CALL BACKS
  ##

  before_action :set_watched_stock, only: [:destroy]

  ##
  ### CRUD (Only index and destroy)
  ##

  # GET /watched_stocks
  # User Watched stock page - where they see all their watched stocks
  # This method will get all the current users watched stocks and display them to them
  def index
    @watched_stocks = current_user.get_watched_stocks.page(params[:page])
  end

  def show
    # TODO temporary to introduce the show links for individual stocks - later will change to actually show the stock alone with details.
    @watched_stocks = current_user.get_watched_stocks.page(params[:page])
    render :index
  end


  # DELETE /watched_stocks/1
  # Destroy a watched stock
  # This method is not heavily used other than in tests
  # Possible use: remove watched stocks that are no longer watched (why keep updating it?)
  # Params
  # @watched_stock - uses id param to get the correct watched stock
  def destroy
    # TODO future feature - job to run nightly to check whether all watched stocks are at least watched by one person - prune any that are not? Need to consider the ramifications of this - may want to keep the stock data to run analysis on
    # Database constraint will prevent a watched stock from being deleted if stock_lists still reference it
    @watched_stock.destroy
    redirect_to watched_stocks_url, notice: t('controller.watched_stocks.flash.destroy.success')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watched_stock
      @watched_stock = WatchedStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watched_stock_params
      # NOTE: add new attributes here to allow them through for creating and updating
      params.require(:watched_stock).permit(:name, :ticker, :current_price)
    end

  # Provides list of params to filter alerts by. Linked to StockAlert model scopes.
  def filtering_params(params)
    params.slice(:with_trigger_status)
  end
end

app/helpers/watched_stocks_helper.rb
module WatchedStocksHelper
end

app/views/watched_stocks/_watched_stock_display.html.erb
<% watched_stock = stock_list_item.watched_stock.decorate %>
<div class="large-4 medium-6 small-12 columns <%= is_end ? 'end' : '' %>">
  <ul class="pricing-table">
    <li class="title"><%= link_to("#{watched_stock.name} (#{watched_stock.ticker})", '#', class: 'stock_info quick_view_stock', :'data-link' => watched_stock.ticker, :'data-reveal-id' => 'more_info_modal') %></li>
    <li class="price"><%= watched_stock.current_price %></li>
    <li class="description"><%= t('views.watched_stocks.watched_stock_display.watching_since', date_time: formatted_created_at(stock_list_item)) %></li>
    <!--<li class="bullet-item">Today's high: </li>-->
    <!--<li class="bullet-item">Today's low: </li>-->
    <li class="bullet-item"><%= pluralize(stock_list_item.stock_alerts.length, t('views.watched_stocks.watched_stock_display.alert')) %></li>
    <li class="cta-button">
      <%= f_row do %>
          <%= f_columns([:small_12]) do %>
              <%= dropdown_helper(watched_stock.class.to_s + watched_stock.id.to_s, t('views.watched_stocks.watched_stock_display.menu.actions'), [
                  link_to(t('views.watched_stocks.watched_stock_display.menu.add_alert'), new_stock_alert_path(alert_for: stock_list_item.id)),
                  link_to(t('views.watched_stocks.watched_stock_display.menu.view_alert'), stock_alerts_path(alert_for: stock_list_item.id)),
                  link_to(t('views.watched_stocks.watched_stock_display.menu.quick_view'), '#', class: 'stock_info', :'data-link' => watched_stock.ticker, :'data-reveal-id' => 'more_info_modal'),
                  link_to(t('views.watched_stocks.watched_stock_display.menu.remove'), stock_list_path(id: stock_list_item), method: :delete, data: {confirm: t('general.confirm.are_you_sure')})
              ]) %>
          <% end %>
      <% end %>
    </li>
  </ul>
</div>

app/views/watched_stocks/index.html.erb
<h2><%= t('views.watched_stocks.index.title') %></h2>
<% if @watched_stocks.empty? %>
    <p><%= t('views.watched_stocks.index.no_watched_stocks') %></p>
<% end %>
<div class="row">
  <% @watched_stocks.each do |stock_list_item| %>
      <%= render 'watched_stock_display', stock_list_item: stock_list_item, is_end: @watched_stocks.last == stock_list_item %>
  <% end %>
</div>
<%= paginate @watched_stocks %>
<%= render 'shared/more_asset_info' %>

<script>
    // On click of a stock_info class link the data-link field contains the ticker and that will be searched and populate a modal.
    $(".stock_info").click(function () {
        var ticker = this.getAttribute("data-link");
        getAssetInfo(ticker, populateAssetInfo);

        // Should we also trigger the modal here instead of the link?
        // $('#search_info_modal').foundation('reveal', 'open');
        // Answer: No, when triggering it via JS it does not know what position to be at when the modal is triggered so the user may not see it
    });
</script>